 /**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * @description
 * @file config.example.js
 * @author: Oskar Yildiz <oskar> 2018-04-22T11:05:01+02:00
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by Oskar Yildiz <oskar> on 2018-04-22T11:05:01+02:00.
 * Last modified by oskar on 2018-04-22T11:05:01+02:00
 *
 */

 const defaultConfig = {
 };

 const devConfig = {
   apiUrl: "http://localhost:4000/api"
 };

 const prodConfig = {
   apiUrl: "https://"
 };

 const envConfig = env => {
   switch (env) {
     case true:
       return { ...defaultConfig, ...devConfig };
     case false:
       return { ...defaultConfig, ...prodConfig };
     default:
       return { defaultConfig, ...prodConfig };
   }
 };

 export default envConfig(__DEV__);
