 /**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * @description
 * @file form.styles.js
 * @author: Oskar Yildiz <oskar> 2018-04-19T17:55:46+02:00
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by Oskar Yildiz <oskar> on 2018-04-19T17:55:46+02:00.
 * Last modified by oskar on 2018-04-19T17:55:46+02:00
 *
 */

export default {
  title: {
    fontSize: 40,
    color: "#394BCF",
    fontWeight: "bold",
    alignSelf: 'center'
  },
  submitBtn: {
    backgroundColor: '#394BCF',
    height: 50,
    width: 325,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 10
  },
  submitBtnText: {
    color: '#fff',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 16
  }
};
