 /**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * @description
 * @file PrimaryButton.js
 * @author: Oskar Yildiz <oskar> 2018-04-20T16:06:45+02:00
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by Oskar Yildiz <oskar> on 2018-04-20T16:06:45+02:00.
 * Last modified by oskar on 2018-04-20T16:06:45+02:00
 *
 */

import { TouchableOpacity, Text } from 'react-native';
import React from 'react';

import constants from '../constants';

const PrimaryButton = ({ title, onPress }) => {
  return (
    <TouchableOpacity style={styles.btn} onPress={onPress}>
      <Text style={styles.btnText}>{title}</Text>
    </TouchableOpacity>
  )
 };

 export default PrimaryButton;

 const styles = {
   btn: {
    backgroundColor: '#394BCF',
    height: 50,
    width: 325,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 6,
    marginTop: '2%'
  },
  btnText: {
    color: '#fff',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 16
  },
 }
