/**
 * This notation was generated by templates.
 * // -------------------------------------------------
 * @description
 * @file index.js
 * @author: Oskar Yildiz <oskar> 2018-02-22T19:30:17+01:00
 * // -------------------------------------------------
 * Make sure this file is part of its proper namespace
 * and project before moving on.
 * // -------------------------------------------------
 * Code-tags conventionally should be used (See below) :
 * TODO - Something that someone need to do.
 * DOING - Self remind for what you are doing.
 * CONSIDER - Reminder to consider a change or addition.
 * BUG - The below section of a code cause a bug.
 * FIXME - The below section of code need to be fixed.
 * HACK - The below section of code is a workaround.
 * XXX - Any notation important enough to consider implementing.
 * CLARIFY - Very incomprehensible section of code below.
 *
 * Created by Oskar Yildiz <oskar> on 2018-02-22T19:30:17+01:00.
 * Last modified by oskar on 2018-02-22T19:30:18+01:00
 *
 */

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { View, Text } from 'react-native';

import commonStyles from '../../styles/common.styles';
import { getFullSchedule } from '../../redux/schedule/actions';

class ScheduleScreen extends Component {
  constructor(props) {
    super(props);
  }

  async componentWillMount() {
    await this.props.getFullSchedule();
  }

  // TODO: Design individual schedule/class component and map through schedule and render each class as that component here
  render() {
    return (
      <View style={commonStyles.container}>
        <Text>Schema</Text>
        {this.props.schedule.schedule && (
          <Text>{JSON.stringify(this.props.schedule.schedule)}</Text>
        )}
      </View>
    );
  }
}

function mapStateToProps(state) {
  return {
    schedule: state.schedule,
    auth: state.auth
  };
}

export default connect(mapStateToProps, { getFullSchedule })(ScheduleScreen);
